
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 14;
  public static final int RCOMMENT = 22;
  public static final int EXCLAMATION = 24;
  public static final int PLUS = 9;
  public static final int BADCHAR = 25;
  public static final int RBRACE = 20;
  public static final int RPAREN = 18;
  public static final int OR = 15;
  public static final int EQUAL = 7;
  public static final int IN = 26;
  public static final int CHAR = 3;
  public static final int IDENTIFIER = 5;
  public static final int INLINECOMMENT = 23;
  public static final int LBRACE = 19;
  public static final int LPAREN = 17;
  public static final int EOF = 0;
  public static final int MULT = 11;
  public static final int LCOMMENT = 21;
  public static final int DIV = 12;
  public static final int SEMICOL = 8;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int LET = 6;
  public static final int BOOL = 4;
  public static final int INTEGER = 2;
  public static final int LESS = 16;
  public static final int POWER = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "CHAR",
  "BOOL",
  "IDENTIFIER",
  "LET",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POWER",
  "AND",
  "OR",
  "LESS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LCOMMENT",
  "RCOMMENT",
  "INLINECOMMENT",
  "EXCLAMATION",
  "BADCHAR",
  "IN"
  };
}

